name: physio_connect
description: A physical therapy application that empowers your recovery.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Packages
  cupertino_icons: ^1.0.6
  
  # Video Support
  video_player: ^2.7.2
  
  # HTTP Client for API calls
  http: ^1.1.0
  
  # Animation (Used in splash screen)
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Include assets
  assets:
    - lib/assets/images/
    - lib/assets/images/app_logo.png
    - assets/videos/vid.mp4
    - assets/icons/1.png
    - assets/icons/2.png
    - assets/icons/3.png
    - assets/icons/4.png
    - assets/icons/5.png
    - assets/icons/6.png
    - assets/icons/7.png
    - assets/icons/8.png
    - assets/icons/9.png
    - assets/icons/10.png

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic